import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";
import "@/styles/globals.css";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body style={{ backgroundColor: "var(--white_a700_b2)" }}>
        <Header />
        <div className="flex pt-[60px]">
          <SideBar />
          <div className="flex-1 p-4">
            <Suspense
              fallback={
                <div className="font-bold bg-green-950">Loading...</div>
              }
            >
              {children}
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  );
}
